scalar JSON
scalar BigInt
scalar BoolOrFloat

enum FriendRequestStatus {
	ACCEPTED
	PENDING
	SENT
	BLOCKED
}

type FriendStatus {
	user: User!
	status: FriendRequestStatus!
	sharedHabits: [Habit!]
}

type User {
	id: ID!
	username: String!
	email: String!
	friends: [FriendStatus!]
	habits: [Habit!]
	avatar: String
}

enum HabitTypes {
	QUANTITY
	DURATION
	BOOLEAN
}

type Habit {
	id: ID!
	private: Boolean
	owner: User
	name: String!
	type: HabitTypes!
	goal: Float
	unit: String
	createdAt: String
	datesCompleted: JSON
	clonedFrom: Habit
	timeScaler: Float
}


type Query {
	me: User
	user(id: ID!): User
	users(part: String): [User!]!
	habit(id: ID!): Habit
	habits(owner: ID): [Habit]
	selectableHabits: [Habit]
	searchUsers(part: String): [User]
}

type Mutation {
	register(username: String!, email: String!, password: String!): User
	login(email: String!, password: String!): String
	addHabit(id: ID, name: String!, type: HabitTypes!, goal: Float, unit: String, datesCompleted: JSON, clonedFrom: ID, private: Boolean): Habit
	deleteHabit(id: ID): Habit
	completeHabit(habitId: ID!, date: BigInt!, degreeOfCompletion: BoolOrFloat): Habit
	addFriend(friendId: ID!, status: FriendRequestStatus!): User
}

