scalar JSON
scalar BigInt
scalar BoolOrFloat

mutation addHabit($id: ID, $name: String!, $type: HabitTypes!, $goal: Float, $unit: String, $datesCompleted: JSON) {
  addHabit(id: $id, name: $name, type: $type, goal: $goal, unit: $unit, datesCompleted: $datesCompleted) {
    id
    name
    type
    goal
    unit
    createdAt
    datesCompleted
    owner {
      id
      username
    }
  }
}
mutation deleteHabit($id: ID) {
  deleteHabit(id: $id) {
    id
    name
    owner {
      id
      username
    }
  }
}

# Complete a habit for a specific date
mutation completeHabit($habitId: ID!, $date: BigInt!, $degreeOfCompletion: BoolOrFloat) {
  completeHabit(habitId: $habitId, date: $date, degreeOfCompletion: $degreeOfCompletion) {
    id
    name
    datesCompleted
  }
}


# Add a friend by ID
mutation addFriend($friendId: ID!) {
  addFriend(friendId: $friendId) {
    id
    username
    friends {
      id
      username
    }
  }
}

# Get the current user
query me {
  me {
    id
    username
    email
    friends {
      id
      username
    }
    habits {
      id
      name
      datesCompleted
    }
  }
}

# Get a user by ID
query user($id: ID!) {
  user(id: $id) {
    id
    username
    email
    friends {
      id
      username
    }
    habits {
      id
      name
      datesCompleted
    }
  }
}

# Get all users
query users {
  users {
    id
    username
    email
  }
}

# Get a habit by ID
query habit($id: ID!) {
  habit(id: $id) {
    id
    name
    type
    goal
    unit
    createdAt
    datesCompleted
    owner {
      id
      username
    }
  }
}

query searchUsers($part: String) {
  searchUsers(part: $part) {
    id,
    username,
    avatar
  }
}

# Get all habits
query habits($owner: ID) {
  habits(owner: $owner) {
    id
    name
    type
    goal
    unit
    createdAt
    datesCompleted
    owner {
      id
      username
    }
  }
}
