fragment UserCore on User {
  id
  username
}

fragment HabitBase on Habit {
  id
  name
  type
  goal
  unit
  createdAt
  datesCompleted
  private
  negative
  owner {
    id
    username
  }
}

fragment UserProfile on User {
  ...UserCore
  email
  friends {
    user {
      ...UserCore
    }
    status
  }
  habits {
    id
    name
    datesCompleted
  }
}

# --- 2. Mutations ---

mutation addHabit(
  $id: ID
  $name: String!
  $type: HabitTypes!
  $goal: Float
  $unit: String
  $datesCompleted: JSON
  $clonedFrom: ID
  $private: Boolean
  $negative: Boolean
) {
  addHabit(
    id: $id
    name: $name
    type: $type
    goal: $goal
    unit: $unit
    datesCompleted: $datesCompleted
    clonedFrom: $clonedFrom
    private: $private
    negative: $negative
  ) {
    ...HabitBase
    clonedFrom {
      ...HabitBase
      completeSfx
    } # 👈 Extends the base fragment with the SFX!
  }
}

mutation deleteHabit($id: ID) {
  deleteHabit(id: $id) {
    id
    name
    owner {
      id
      username
    }
  }
}

mutation completeHabit(
  $habitId: ID!
  $date: BigInt!
  $degreeOfCompletion: BoolOrFloat
) {
  completeHabit(
    habitId: $habitId
    date: $date
    degreeOfCompletion: $degreeOfCompletion
  ) {
    id
    name
    datesCompleted
  }
}

mutation addFriend($friendId: ID!, $status: FriendRequestStatus!) {
  addFriend(friendId: $friendId, status: $status) {
    id
    username
    friends {
      user {
        username
      }
      status
    }
  }
}

# --- 3. Queries ---

query me {
  me {
    ...UserProfile
  }
}
query user($id: ID!) {
  user(id: $id) {
    ...UserProfile
  }
}
query users {
  users {
    id
    username
    email
  }
}
query searchUsers($part: String) {
  searchUsers(part: $part) {
    id
    username
    avatar
  }
}
query selectableHabits {
  selectableHabits {
    id
    name
    type
    goal
    unit
  }
}

query habit($id: ID!) {
  habit(id: $id) {
    ...HabitBase
    clonedFrom {
      ...HabitBase
      completeSfx
    } # 👈 Extends the base fragment with the SFX!
  }
}

query habits($owner: ID) {
  habits(owner: $owner) {
    ...HabitBase
    clonedFrom {
      ...HabitBase
      completeSfx
    }
  }
}
